services:
  - type: web
    plan: free
    name: FileRenameBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/kavisoorai420/Rename-Bot-4GB.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false 
      - key: BOT_PICS
        sync: false
      - key: LOG_CHANNEL
        sync: false   
      -key: FORCE_SUBS
        sync: false
       -key: BOT_USERNAME
        sync: false
        
    autoDeploy: false
